#!/bin/bash

# Pass nginx yesterday's logs to webalizer and then compress them

. "/etc/linuxfr/conf.sh"
LOG_DATE=$(date +'%Y/%m/%d' -d 'yesterday')

# run the daily stats, and shut down some useless warnings
webalizer -c $WEBALIZER_CONF 2>&1 | grep -vE "String exceeds|Truncating oversized"

# compress the logs and move them out of the way
cd $WEBLOGS_DIR
mkdir -p $LOG_DATE

cd $WEBALIZER_INPUT

for logfile in access.log error.log
do
        if [ -f ${logfile}.1 ]; then
                xz ${logfile}.1 && mv ${logfile}.1.xz ${WEBLOGS_DIR}/${LOG_DATE}/${logfile}.xz
        fi
done
