#!/usr/bin/env ruby
# Generate the nginx configuration for a vhost

require 'erb'


if ARGV.empty?
  $stderr.puts "Usage: ./path/to/generator.rb env > sites-available/vhost"
  $stderr.puts "       where env is local, alpha or production"
  exit -1
end

case env = ARGV.first
when "local"
  user    = "nono"
  vserver = "nono"
  fqdn    = "dlfp.lo"
when "alpha"
  user    = "alpha"
  vserver = "alpha"
  fqdn    = "alpha.linuxfr.org"
when "production"
  user    = "linuxfr"
  vserver = "prod"
  fqdn    = "linuxfr.org"
end

# Gruikkkkk
puts ERB.new(DATA.read).result(binding)

__END__
# Please do not edit: this file was generated by conf/nginx/generator.rb

upstream linuxfr-frontend {
    server unix:/var/www/<%= user %>/<%= env %>/shared/tmp/sockets/<%= env %>.sock fail_timeout=0;
}

upstream board-frontend {
    server unix:/var/www/<%= user %>/board/board.sock;
}

upstream epub-frontend {
    server 127.0.0.1:9000;
}


server {
    server_name <%= fqdn %>;
    access_log /data/<%= vserver %>/logs/<%= user %>/access.log;
    error_log /data/<%= vserver %>/logs/<%= user %>/error.log error;
    root /var/www/<%= user %>/<%= env %>/current/public;

    listen 443 default_server ssl;

    add_header X-Content-Type-Options nosniff;

    proxy_max_temp_file_size 0;
    client_max_body_size 2M;

    proxy_intercept_errors on;
    error_page  404              /errors/400.html;
    error_page  500 502 503 504  /errors/500.html;

    merge_slashes on;
    keepalive_timeout 5;

    set $redirect_to_https $cookie_https/$scheme;
    if ($redirect_to_https = '1/http') {
        rewrite ^(.*)$ https://<%= fqdn %>$1 break;
    }

    # Dispatching
    location ^~ /images/load/ {
        autoindex on;
        expires 5m;
    }

    location ~* \.epub$ {
        proxy_buffering off;
        proxy_pass http://epub-frontend;
    }

    location ~* \.(css|js|ico|gif|jpe?g|png|svg|xcf|ttf|otf|dtd)$ {
        expires 10d;
    }
<% if env == "alpha" %>
    location = /robots.txt {
        rewrite ^(.*)$ /system/$1 last;
    }
<% end %>
    location ~* ^/(fonts|images|javascripts|stylesheets) {
        autoindex on;
        break;
    }

    location ^~ /b/ {
        proxy_buffering off;
        proxy_pass http://board-frontend;
    }

    location ^~ /webalizer {
        root /data/<%= vserver %>/logs;
    }

    # Don't try to respond to PHP/ASP/Apple pages
    location ~* \.(php|asp|aspx|jsp|cgi|labels.rdf|apple-touch-icon(-precomposed)?.png)$ {
      return 410;
    }

    location / {
        # Redirections to preserve templeet URL
        rewrite ^/(pub|my|wap|pda|i|interviews|newsletter|rdf|sidebar|usenet)(/.*)?$ / permanent;
        rewrite ^/backend/news-homepage/rss20.rss$ /backend-news.rss break;
        rewrite ^.*\.rss$ /backend.rss break;
        rewrite ^/\d+/\d+/\d+/(\d+)\.html$ /news/$1 permanent;
        rewrite ^/(\d+/\d+/\d+)/index.html$ /$1 permanent;
        rewrite ^/topics/([^,./]*)(,.*)?(.html)?$ /section/$1 permanent;
        rewrite ^/~([^/]*)/?$ /users/$1 permanent;
        rewrite ^/~([^/]*)/(\d+)\.html$ /users/$1/journaux/$2 permanent;
        rewrite ^/~([^/]*)/news.*$ /users/$1/news permanent;
        rewrite ^/~([^/]*)/forums.*$ /users/$1/posts permanent;
        rewrite ^/~([^/]*)/tracker.*$ /users/$1/suivi permanent;
        rewrite ^/~([^/]*)/comments.*$ /users/$1/comments permanent;
        rewrite ^/forums/(\d+)/(\d+)\.html$ /forums/$1/posts/$2 permanent;
        rewrite ^/forums/(\d+)\.+$ /forums/$1 permanent;
        rewrite ^/journal.*$ /journaux permanent;
        rewrite ^/tracker.*$ /suivi permanent;
        rewrite ^/aide.+$ /aide permanent;
        rewrite ^/users/?$ /tableau-de-bord permanent;
        rewrite ^/dons.*$ /faire_un_don permanent;
        rewrite ^/moderateurs/moderation.html$ /regles_de_moderation permanent;
        rewrite ^/moderateurs.*$ /team permanent;
        rewrite ^/redacteurs.*$ /redaction permanent;
        rewrite ^/board/remote.xml$ /board/index.xml permanent;
        rewrite ^/board.xml$ /board/index.xml permanent;
        rewrite ^/bouchot.*$ /board permanent;
        rewrite ^/logos\.html$ /images/logos/ permanent;
        rewrite ^/submit.html$ /news/nouveau permanent;
        rewrite ^/association/index.html$ /informations permanent;

        try_files $uri /pages/$uri /pages/$uri.html @dynamic;
    }

    location @dynamic {
        if (-f $document_root/system/maintenance.html ) {
            error_page 503 /system/maintenance.html;
            return 503;
        }

        proxy_set_header X_FORWARDED_PROTO $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://linuxfr-frontend;
    }

    location /tips {
      # Redirections
      rewrite ^/tips/1.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-un-texte-en-minuscule permanent;
      rewrite ^/tips/2.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-couper-les-lignes-trop-longues permanent;
      rewrite ^/tips/3.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-lister-un-r%C3%A9pertoire permanent;
      rewrite ^/tips/4.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-ouvrir-une-fen%C3%AAtre permanent;
      rewrite ^/tips/5.html$ /forums/astucesdivers/posts/x-window-exploiter-au-mieux-son-%C3%A9cran permanent;
      rewrite ^/tips/6.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-coloriser-vos-fichiers permanent;
      rewrite ^/tips/7.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-des-espaces-plut%C3%B4t-que-des-tabulations permanent;
      rewrite ^/tips/8.html$ /forums/astucesdivers/posts/editeur-changer permanent;
      rewrite ^/tips/9.html$ /forums/astucesdivers/posts/debian-recompiler-un-package-debian permanent;
      rewrite ^/tips/10.html$ /forums/astucesdivers/posts/terminal-reconnecter-un-process-au-terminal permanent;
      rewrite ^/tips/11.html$ /forums/astucesdivers/posts/terminal-recompression-jpeg permanent;
      rewrite ^/tips/12.html$ /forums/astucesdivers/posts/terminal-changer-les-titres-des-fen%C3%AAtres-%C3%A0-la-vol%C3%A9e permanent;
      rewrite ^/tips/13.html$ /forums/astucesdivers/posts/terminal-lancer-une-appli-puis-se-d%C3%A9connecter permanent;
      rewrite ^/tips/14.html$ /forums/astucesdivers/posts/terminal-le-nombre-de-pages-dans-un-document-postscript permanent;
      rewrite ^/tips/15.html$ /forums/astucesdivers/posts/terminal-la-liste-des-utilisateurs-sur-5-colonnes permanent;
      rewrite ^/tips/16.html$ /forums/astucesdivers/posts/debian-la-liste-des-mots-communs-%C3%A0-deux-langues permanent;
      rewrite ^/tips/17.html$ /forums/astucesdivers/posts/terminal-la-redirection-des-fichiers-sous-bash permanent;
      rewrite ^/tips/18.html$ /forums/astucesdivers/posts/terminal-lancer-plusieurs-programmes-dans-un-seul-terminal permanent;
      rewrite ^/tips/19.html$ /forums/astucesdivers/posts/debian-recompiler-un-paquet-debian permanent;
      rewrite ^/tips/20.html$ /forums/astucesdivers/posts/x-window-copie-du-clipboard permanent;
      rewrite ^/tips/21.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-digests-sous-gnus permanent;
      rewrite ^/tips/22.html$ /forums/astucesdivers/posts/debian-extraire-une-archive-dun-paquet-debian permanent;
      rewrite ^/tips/23.html$ /forums/astucesdivers/posts/terminal-eviter-les-check-forced permanent;
      rewrite ^/tips/24.html$ /forums/astucesdivers/posts/terminal-virer-des-fichiers-superflus permanent;
      rewrite ^/tips/25.html$ /forums/astucesdivers/posts/terminal-alias-avec-bash permanent;
      rewrite ^/tips/26.html$ /forums/astucesdivers/posts/terminal-les-variables-denvironnement permanent;
      rewrite ^/tips/27.html$ /forums/astucesdivers/posts/terminal-changements-rapides-avec-sed permanent;
      rewrite ^/tips/28.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-faire-une-recherche-dune-expression-dans-plusie permanent;
      rewrite ^/tips/29.html$ /forums/astucesdivers/posts/terminal-en-cas-de-freeze-de-la-machine permanent;
      rewrite ^/tips/30.html$ /forums/astucesdivers/posts/x-window-balader-un-bureau-en-campagne permanent;
      rewrite ^/tips/31.html$ /forums/astucesdivers/posts/terminal-ne-plus-taper-ses-mots-de-passe-avec-ssh permanent;
      rewrite ^/tips/32.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-un-pwd-diff%C3%A9rent-par-fen%C3%AAtre-ouverte permanent;
      rewrite ^/tips/33.html$ /forums/astucesdivers/posts/courrielexim-exim-et-les-frozens permanent;
      rewrite ^/tips/34.html$ /forums/astucesdivers/posts/terminal-faites-du-hot-plug-avec-vos-racks-ide permanent;
      rewrite ^/tips/35.html$ /forums/astucesdivers/posts/terminal-pour-renommer-des-fichiers-avec-des-chiffres permanent;
      rewrite ^/tips/36.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-incrementer-un-nombre permanent;
      rewrite ^/tips/37.html$ /forums/astucesdivers/posts/terminal-lilo-%C3%A0-partir-dune-disquette-de-boot permanent;
      rewrite ^/tips/38.html$ /forums/astucesdivers/posts/terminal-backup-simple-et-pas-cher permanent;
      rewrite ^/tips/39.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-r%C3%A9cup%C3%A9rer-le-resultat-dune-commande permanent;
      rewrite ^/tips/42.html$ /forums/astucesdivers/posts/terminal-make-jx-ou-comment-ralentiracceler-une-compilation permanent;
      rewrite ^/tips/41.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-identifier-les-tabulation-et-les-espaces permanent;
      rewrite ^/tips/43.html$ /forums/astucesdivers/posts/terminal-le-cdpath-pour-les-feignans permanent;
      rewrite ^/tips/44.html$ /forums/astucesdivers/posts/terminal-raccourcis-clavier-bash permanent;
      rewrite ^/tips/45.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-majuculesminuscules permanent;
      rewrite ^/tips/46.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-majusculesminuscules-2 permanent;
      rewrite ^/tips/47.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-chercher-un-mot permanent;
      rewrite ^/tips/48.html$ /forums/astucesdivers/posts/perl-passer-de-sed-a-perl permanent;
      rewrite ^/tips/49.html$ /forums/astucesdivers/posts/terminal-accel%C3%A9rer-le-syst%C3%A8me-de-fichier permanent;
      rewrite ^/tips/50.html$ /forums/astucesdivers/posts/terminal-comment-se-r%C3%A9partissent-les-donn%C3%A9es permanent;
      rewrite ^/tips/51.html$ /forums/astucesdivers/posts/terminal-cr%C3%A9er-une-image-iso permanent;
      rewrite ^/tips/52.html$ /forums/astucesdivers/posts/terminal-renommer-une-s%C3%A9rie-de-fichiers-sous-unix permanent;
      rewrite ^/tips/53.html$ /forums/astucesdivers/posts/terminal-recup%C3%A9rer-lilo-suite permanent;
      rewrite ^/tips/54.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-f1-donne-de-laide-avec-emacs permanent;
      rewrite ^/tips/55.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-faire-un-copiercoller-avec-emacsxemacs permanent;
      rewrite ^/tips/170.html$ /forums/astucesdivers/posts/x-window-gdm-et-windowmaker permanent;
      rewrite ^/tips/57.html$ /forums/astucesdivers/posts/debian-freezer-des-paquets-avec-dpkg permanent;
      rewrite ^/tips/70.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-illuminer-les-mots-qui-vous-int%C3%A9ressent permanent;
      rewrite ^/tips/63.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-fonctions-c permanent;
      rewrite ^/tips/67.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-le-de-vi permanent;
      rewrite ^/tips/60.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-s%C3%A9lection-dune-fonction permanent;
      rewrite ^/tips/66.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-oui-ou-non permanent;
      rewrite ^/tips/69.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-numeroter-les-lignes-sous-vi permanent;
      rewrite ^/tips/72.html$ /forums/astucesdivers/posts/terminal-term-bloqu%C3%A9 permanent;
      rewrite ^/tips/71.html$ /forums/astucesdivers/posts/terminal-ajouter-lheuredate-dun-affichage permanent;
      rewrite ^/tips/68.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-ouvrir-les-fichiers-compress%C3%A9s permanent;
      rewrite ^/tips/79.html$ /forums/astucesdivers/posts/terminal-bien-lister-ses-fichiers permanent;
      rewrite ^/tips/76.html$ /forums/astucesdivers/posts/editeur-comment-%C3%A9diter-un-script-python-avec-gnumeric permanent;
      rewrite ^/tips/74.html$ /forums/astucesdivers/posts/editeur-de-dos-%C3%A0-unix-sous-joe permanent;
      rewrite ^/tips/77.html$ /forums/astucesdivers/posts/terminal-%C3%A9teindre-proprement-en-mode-texte permanent;
      rewrite ^/tips/78.html$ /forums/astucesdivers/posts/x-window-contr%C3%B4ler-la-souris-avec-le-pav%C3%A9-num%C3%A9rique permanent;
      rewrite ^/tips/80.html$ /forums/astucesdivers/posts/terminal-enchainer-les-r%C3%A9pertoires permanent;
      rewrite ^/tips/81.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-travailler-sur-une-r%C3%A9gion-xemacs permanent;
      rewrite ^/tips/82.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-travailler-sur-une-r%C3%A9gion-xemacs--2 permanent;
      rewrite ^/tips/83.html$ /forums/astucesdivers/posts/terminal-se-d%C3%A9loguer-rapide permanent;
      rewrite ^/tips/85.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-les-registres-emacs permanent;
      rewrite ^/tips/87.html$ /forums/astucesdivers/posts/terminal-xterm-la-souris permanent;
      rewrite ^/tips/88.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-tous-les-raccourcis-clavier-utiles-emacsxemacs permanent;
      rewrite ^/tips/89.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-ouvrir-un-fichier-dans-une-fenetre-emacs permanent;
      rewrite ^/tips/90.html$ /forums/astucesdivers/posts/terminal-debug-de-scripts-bash permanent;
      rewrite ^/tips/91.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-switch-buffer permanent;
      rewrite ^/tips/92.html$ /forums/astucesdivers/posts/terminal-programmer-larret permanent;
      rewrite ^/tips/93.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-coloriser-son-code permanent;
      rewrite ^/tips/94.html$ /forums/astucesdivers/posts/debian-ssh-comme-port-forwarder permanent;
      rewrite ^/tips/95.html$ /forums/astucesdivers/posts/terminal-s%C3%A9curiser-vos-terms permanent;
      rewrite ^/tips/96.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-joindre-un-fichier permanent;
      rewrite ^/tips/97.html$ /forums/astucesdivers/posts/terminal-ne-pas-afficher-le-contenu-dun-r%C3%A9pertoire-avec-ls permanent;
      rewrite ^/tips/121.html$ /forums/astucesdivers/posts/terminal-faire-marcher-des-scripts-sh-non-posix-sur-linux permanent;
      rewrite ^/tips/99.html$ /forums/astucesdivers/posts/terminal-comment-choisir-le-gcc-quil-vous-faut permanent;
      rewrite ^/tips/100.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-savoir-rester-modeste-vis-%C3%A0-vis-demacs permanent;
      rewrite ^/tips/101.html$ /forums/astucesdivers/posts/terminal-convertir-une-animation-tga-en-gif permanent;
      rewrite ^/tips/102.html$ /forums/astucesdivers/posts/terminal-protection-des-fichiers-et-ext2 permanent;
      rewrite ^/tips/103.html$ /forums/astucesdivers/posts/x-window-changer-automatiquement-les-th%C3%AAmes-wm permanent;
      rewrite ^/tips/122.html$ /forums/astucesdivers/posts/terminal-cest-cool permanent;
      rewrite ^/tips/123.html$ /forums/astucesdivers/posts/terminal-mettez-vous-%C3%A0-lheure permanent;
      rewrite ^/tips/105.html$ /forums/astucesdivers/posts/debian-processus-dinitialisation permanent;
      rewrite ^/tips/106.html$ /forums/astucesdivers/posts/terminal-monter-des-images-iso permanent;
      rewrite ^/tips/107.html$ /forums/astucesdivers/posts/terminal-vider-un-fichier-cr%C3%A9er-un-fichier-vide permanent;
      rewrite ^/tips/108.html$ /forums/astucesdivers/posts/terminal-du-bon-ordre-des-redirections permanent;
      rewrite ^/tips/119.html$ /forums/astucesdivers/posts/mail-edition-dun-mail-sous-vim permanent;
      rewrite ^/tips/120.html$ /forums/astucesdivers/posts/terminal-effacer-machin permanent;
      rewrite ^/tips/111.html$ /forums/astucesdivers/posts/mail-cyrus-veut-plus-rien-savoir permanent;
      rewrite ^/tips/112.html$ /forums/astucesdivers/posts/mail-mutt-et-vim permanent;
      rewrite ^/tips/113.html$ /forums/astucesdivers/posts/mail-a-la-lecture-dun-mail-sous-mutt permanent;
      rewrite ^/tips/114.html$ /forums/astucesdivers/posts/x-window-un-fond-d%C3%A9cran-vivant permanent;
      rewrite ^/tips/115.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-vim-en-multi-fichier permanent;
      rewrite ^/tips/116.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-autocompletion-sous-xemacs permanent;
      rewrite ^/tips/117.html$ /forums/astucesdivers/posts/terminal-la-ponctuation-espagnole permanent;
      rewrite ^/tips/118.html$ /forums/astucesdivers/posts/x-window-pour-conna%C3%AEtre-la-version-de-votre-serveur-xfree permanent;
      rewrite ^/tips/124.html$ /forums/astucesdivers/posts/terminal-savoir-rapido-quels-services-r%C3%A9seau-sont-activ%C3%A9s permanent;
      rewrite ^/tips/125.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-incr%C3%A9ment permanent;
      rewrite ^/tips/126.html$ /forums/astucesdivers/posts/terminal-jar-gigogne permanent;
      rewrite ^/tips/127.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-tetris-sous-xemacs permanent;
      rewrite ^/tips/128.html$ /forums/astucesdivers/posts/x-window-mettre-l%C3%A9cran-en-veille permanent;
      rewrite ^/tips/344.html$ /forums/astucesdivers/posts/terminal-booter-sur-un-disque-usb permanent;
      rewrite ^/tips/403.html$ /forums/astucesdivers/posts/webmozilla-acc%C3%A9l%C3%A9rer-la-vitesse-daffichage-des-pages-web permanent;
      rewrite ^/tips/346.html$ /forums/astucesdivers/posts/terminal-gentoo-quickpkg-sauvegarde-vos-compilations permanent;
      rewrite ^/tips/347.html$ /forums/astucesdivers/posts/xkde-type-ahead-find-sous-konqueror permanent;
      rewrite ^/tips/131.html$ /forums/astucesdivers/posts/terminal-tunnel-http permanent;
      rewrite ^/tips/132.html$ /forums/astucesdivers/posts/terminal-ajouter-un-p%C3%A9riph-scsi permanent;
      rewrite ^/tips/133.html$ /forums/astucesdivers/posts/terminal-jetez-votre-ancien-nohup permanent;
      rewrite ^/tips/134.html$ /forums/astucesdivers/posts/terminal-lilo-graphique permanent;
      rewrite ^/tips/135.html$ /forums/astucesdivers/posts/terminal-compl%C3%A9tion-avec-gnu-bash permanent;
      rewrite ^/tips/136.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-les-accents-en-fran%C3%A7ais permanent;
      rewrite ^/tips/137.html$ /forums/astucesdivers/posts/terminal-upgrader-son-bios permanent;
      rewrite ^/tips/138.html$ /forums/astucesdivers/posts/x-window-raccourcis-sur-les-applis-gtk permanent;
      rewrite ^/tips/139.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-lancer-des-commandes-shell-%C3%A0-partir-de-vi permanent;
      rewrite ^/tips/140.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-compiler-votre-emacs permanent;
      rewrite ^/tips/141.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-fonds-clairs-et-fonds-sombres permanent;
      rewrite ^/tips/142.html$ /forums/astucesdivers/posts/x-window-afficher-avec-xosd-les-titres-des-chansons-xmms permanent;
      rewrite ^/tips/165.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-lautocompl%C3%A9tion-sous-vim permanent;
      rewrite ^/tips/144.html$ /forums/astucesdivers/posts/x-window-d%C3%A9bloquer-x-window-avec-sigusr1 permanent;
      rewrite ^/tips/145.html$ /forums/astucesdivers/posts/terminal-annuler-un-reboot-dans-lurgence permanent;
      rewrite ^/tips/146.html$ /forums/astucesdivers/posts/x-window-konqueror-d%C3%A9filement-automatique permanent;
      rewrite ^/tips/166.html$ /forums/astucesdivers/posts/x-window-gdm-et-plusieurs-sessions-x-simultan%C3%A9es permanent;
      rewrite ^/tips/167.html$ /forums/astucesdivers/posts/x-window-xinitrc-pour-%C3%A9viter-quun-crash-de-windowmanager-fer permanent;
      rewrite ^/tips/168.html$ /forums/astucesdivers/posts/terminal-bash-et-la-console-de-kde permanent;
      rewrite ^/tips/169.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-indentation-sous-vim permanent;
      rewrite ^/tips/148.html$ /forums/astucesdivers/posts/terminal-imprimer-un-page-du-man permanent;
      rewrite ^/tips/149.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-emacs-dans-un-seul-terminal permanent;
      rewrite ^/tips/150.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-complement-sur-le-texte-en-minuscule permanent;
      rewrite ^/tips/151.html$ /forums/astucesdivers/posts/terminal-comment-faire-un-livre-a-partir-dun-postscript permanent;
      rewrite ^/tips/152.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-ajouter-supprimer-un-rectangle-dans-du-texte permanent;
      rewrite ^/tips/153.html$ /forums/astucesdivers/posts/x-window-apr%C3%A8s-un-retour-de-veille-le-multim%C3%A9dia-d%C3%A9bloque-av permanent;
      rewrite ^/tips/154.html$ /forums/astucesdivers/posts/terminal-renomer-rapidement-des-fichiers permanent;
      rewrite ^/tips/155.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-la-recherche-encore-plus-simple-sous-vim permanent;
      rewrite ^/tips/157.html$ /forums/astucesdivers/posts/terminal-votre-cd-rw-en-lecture-%C3%A9criture permanent;
      rewrite ^/tips/158.html$ /forums/astucesdivers/posts/x-window-modifier-les-bindkeys-sous-enlightement permanent;
      rewrite ^/tips/159.html$ /forums/astucesdivers/posts/terminal-utiliser-mozilla-%C3%A0-travers-un-tunnel-ssh permanent;
      rewrite ^/tips/160.html$ /forums/astucesdivers/posts/x-window-obtenir-les-accents-bizarres-quand-on-a-pas-le-clavie permanent;
      rewrite ^/tips/161.html$ /forums/astucesdivers/posts/terminal-speedtouch-usb-mandrake-91 permanent;
      rewrite ^/tips/162.html$ /forums/astucesdivers/posts/x-window-script-gimp-anti-zyeux-rouges permanent;
      rewrite ^/tips/163.html$ /forums/astucesdivers/posts/x-window-regarder-vite-la-t%C3%A9l%C3%A9-au-d%C3%A9marrage permanent;
      rewrite ^/tips/164.html$ /forums/astucesdivers/posts/x-window-installer-le-pilote-nvidiagforce-sous-mandrake-91 permanent;
      rewrite ^/tips/171.html$ /forums/astucesdivers/posts/terminal-transformer-son-palm-en-vt permanent;
      rewrite ^/tips/172.html$ /forums/astucesdivers/posts/terminal-convertir-des-fichier-ra-rm-ou-autres-en-wav permanent;
      rewrite ^/tips/174.html$ /forums/astucesdivers/posts/debian-compl%C3%A9tions-bash-et-debian permanent;
      rewrite ^/tips/175.html$ /forums/astucesdivers/posts/x-window-pages-de-man-sous-kde permanent;
      rewrite ^/tips/176.html$ /forums/astucesdivers/posts/xkde-scripter-le-terminal-sous-kde permanent;
      rewrite ^/tips/182.html$ /forums/astucesdivers/posts/terminal-d%C3%A9connexion-automatique permanent;
      rewrite ^/tips/177.html$ /forums/astucesdivers/posts/debian-une-utilisation-de-apt-listbugs permanent;
      rewrite ^/tips/197.html$ /forums/astucesdivers/posts/terminal-compiler-du-c-%C3%A0-la-vol%C3%A9e permanent;
      rewrite ^/tips/179.html$ /forums/astucesdivers/posts/terminal-%C3%A9viter-de-perdre-le-controle-dune-machine-distante permanent;
      rewrite ^/tips/180.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-si-votre-vim-est-mal-dress%C3%A9 permanent;
      rewrite ^/tips/184.html$ /forums/astucesdivers/posts/terminal-suivre-l%C3%A9tat-du-syst%C3%A8me-tout-en-manipulant permanent;
      rewrite ^/tips/185.html$ /forums/astucesdivers/posts/terminal-bzip2-et-tar-sous-mac-os-x permanent;
      rewrite ^/tips/186.html$ /forums/astucesdivers/posts/terminal-marre-de-taper-les-uid-des-process permanent;
      rewrite ^/tips/187.html$ /forums/astucesdivers/posts/web-sidebar-mozilla-pour-r%C3%A9f%C3%A9rence-css-xslt-html-dom-et-jav permanent;
      rewrite ^/tips/188.html$ /forums/astucesdivers/posts/terminal-extraire-le-contenu-dun-fichier-rpm permanent;
      rewrite ^/tips/189.html$ /forums/astucesdivers/posts/terminal-lire-du-ms-word-en-console permanent;
      rewrite ^/tips/190.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-pleins-de-modules-int%C3%A9ressants-pour-emacs permanent;
      rewrite ^/tips/191.html$ /forums/astucesdivers/posts/x-window-r%C3%A9cup%C3%A9rer-le-point-du-pav%C3%A9-sous-rh9 permanent;
      rewrite ^/tips/192.html$ /forums/astucesdivers/posts/x-window-d%C3%A9marage-de-galeon-hyper-rapide permanent;
      rewrite ^/tips/193.html$ /forums/astucesdivers/posts/editeur-synchro-locale-dun-site-web-statique permanent;
      rewrite ^/tips/194.html$ /forums/astucesdivers/posts/debian-synth%C3%A8se-et-test-de-page-web permanent;
      rewrite ^/tips/195.html$ /forums/astucesdivers/posts/terminal-%C3%A9viter-le-chargement-de-certains-modules permanent;
      rewrite ^/tips/198.html$ /forums/astucesdivers/posts/x-window-curseurs-transparents-avec-xfree43x permanent;
      rewrite ^/tips/199.html$ /forums/astucesdivers/posts/terminal-copier-tout-le-contenu-dun-r%C3%A9pertoire-vers-un-autre permanent;
      rewrite ^/tips/200.html$ /forums/astucesdivers/posts/mail-filtrer-les-fichiers-attach%C3%A9s-sur-les-couriels-entrants permanent;
      rewrite ^/tips/201.html$ /forums/astucesdivers/posts/x-window-redimensionner-la-police-votre-%C3%A9mulateur-de-terminal permanent;
      rewrite ^/tips/202.html$ /forums/astucesdivers/posts/terminal-mince-jai-ferm%C3%A9-la-fen%C3%AAtre-qui-contenait-xxxx permanent;
      rewrite ^/tips/203.html$ /forums/astucesdivers/posts/terminal-une-imprimante-pdf-en-2-coups-de-cuill%C3%A8res-%C3%A0-pot permanent;
      rewrite ^/tips/204.html$ /forums/astucesdivers/posts/terminal-pipe-sur-stderr permanent;
      rewrite ^/tips/205.html$ /forums/astucesdivers/posts/debian-probl%C3%A8me-de-persistence-avec-votre-modem-usb permanent;
      rewrite ^/tips/206.html$ /forums/astucesdivers/posts/x-window-afficher-correctement-les-accents-dans-xchat permanent;
      rewrite ^/tips/207.html$ /forums/astucesdivers/posts/web-europe-1-en-direct-stream-avec-mplayer permanent;
      rewrite ^/tips/208.html$ /forums/astucesdivers/posts/web-indiquer-toute-une-plage-dadresses-ip-dans-le-no-proxy-f permanent;
      rewrite ^/tips/209.html$ /forums/astucesdivers/posts/x-window-suppression-du-mode-veille-du-screen permanent;
      rewrite ^/tips/211.html$ /forums/astucesdivers/posts/web-privoxy-naime-pas-spip permanent;
      rewrite ^/tips/212.html$ /forums/astucesdivers/posts/terminal-test-cpu-dans-nagios permanent;
      rewrite ^/tips/213.html$ /forums/astucesdivers/posts/xkde-changer-votre-fond-d%C3%A9cran-avec-un-script permanent;
      rewrite ^/tips/214.html$ /forums/astucesdivers/posts/terminal-mettre-des-commandes-en-queue permanent;
      rewrite ^/tips/215.html$ /forums/astucesdivers/posts/terminal-lancer-une-commande-qui-%C3%A9choue-parfois-en-%C3%A9tant-s%C3%BBr-q permanent;
      rewrite ^/tips/216.html$ /forums/astucesdivers/posts/web-filtrer-la-publicit%C3%A9 permanent;
      rewrite ^/tips/217.html$ /forums/astucesdivers/posts/x-window-clavier-avec-des-caract%C3%A8res-sp%C3%A9cifiques permanent;
      rewrite ^/tips/218.html$ /forums/astucesdivers/posts/xkde-choisir-le-bureau-virtuel-de-son-application permanent;
      rewrite ^/tips/225.html$ /forums/astucesdivers/posts/x-window-avoir-le-clavier-en-azerty permanent;
      rewrite ^/tips/220.html$ /forums/astucesdivers/posts/x-window-les-curseurs-color%C3%A9s-et-transparents permanent;
      rewrite ^/tips/221.html$ /forums/astucesdivers/posts/webmozilla-editer-%C3%A0-la-vol%C3%A9e-le-css-de-la-page-en-cours-dans permanent;
      rewrite ^/tips/222.html$ /forums/astucesdivers/posts/terminal-sauthentifier-une-et-une-seule-fois-avec-ssh permanent;
      rewrite ^/tips/223.html$ /forums/astucesdivers/posts/web-mozilla-au-clavier-plus-vite permanent;
      rewrite ^/tips/224.html$ /forums/astucesdivers/posts/terminal-utilisation-de-ssh-sans-assistance-humaine permanent;
      rewrite ^/tips/226.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-marre-des-m permanent;
      rewrite ^/tips/227.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-nouveau-sous-vim permanent;
      rewrite ^/tips/228.html$ /forums/astucesdivers/posts/debian-activer-les-options-du-noyau-au-d%C3%A9marrage permanent;
      rewrite ^/tips/229.html$ /forums/astucesdivers/posts/debian-faire-d%C3%A9marrer-une-debian-plus-vite permanent;
      rewrite ^/tips/230.html$ /forums/astucesdivers/posts/terminal-fichier-log-ou-affichage permanent;
      rewrite ^/tips/231.html$ /forums/astucesdivers/posts/x-window-titre-dynamique-pour-le-term permanent;
      rewrite ^/tips/232.html$ /forums/astucesdivers/posts/xkde-placer-nimporte-quelle-application-dans-la-barre-de-not permanent;
      rewrite ^/tips/233.html$ /forums/astucesdivers/posts/debian-faire-rena%C3%AEtre-un-paquet-de-ses-cendres permanent;
      rewrite ^/tips/234.html$ /forums/astucesdivers/posts/webmozilla-ouvrir-une-page-html-dans-mozilla-firebird-quil permanent;
      rewrite ^/tips/235.html$ /forums/astucesdivers/posts/terminal-enregistrer-la-radio-en-mp3-ou-en-ogg permanent;
      rewrite ^/tips/272.html$ /forums/astucesdivers/posts/debian-%C3%A9couter-sa-musique-diff%C3%A9rement permanent;
      rewrite ^/tips/237.html$ /forums/astucesdivers/posts/xkde-menu-contextuel-de-konqueror permanent;
      rewrite ^/tips/238.html$ /forums/astucesdivers/posts/debian-r%C3%A9installer-sa-debian-presque-%C3%A0-lidentique permanent;
      rewrite ^/tips/240.html$ /forums/astucesdivers/posts/terminal-mpc-relister-tout-ses-fichier-musicaux permanent;
      rewrite ^/tips/241.html$ /forums/astucesdivers/posts/terminal-choisir-son-profil-reseau-au-d%C3%A9marrage-redhat permanent;
      rewrite ^/tips/271.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-lancer-une-commande-sur-tous-les-buffers-avec-vim permanent;
      rewrite ^/tips/243.html$ /forums/astucesdivers/posts/terminal-fichiers-zip-morcel%C3%A9s permanent;
      rewrite ^/tips/244.html$ /forums/astucesdivers/posts/debian-acc%C3%A9lerer-le-chargement-des-applis-sous-debian-unstable permanent;
      rewrite ^/tips/270.html$ /forums/astucesdivers/posts/debian-comment-installer-une-debian-par-cd-sur-un-pc-qui-ne-pe permanent;
      rewrite ^/tips/248.html$ /forums/astucesdivers/posts/xkde-d%C3%A9marrer-des-programmes-au-d%C3%A9marrage-de-kde-sous-mandra permanent;
      rewrite ^/tips/249.html$ /forums/astucesdivers/posts/debian-proc%C3%A9dure-de-changement-de-r%C3%A9solution-et-de-bootsplash permanent;
      rewrite ^/tips/250.html$ /forums/astucesdivers/posts/x-window-funky-desktop-3d permanent;
      rewrite ^/tips/251.html$ /forums/astucesdivers/posts/x-window-bureaux-virtuels-sous-os-x3-panther permanent;
      rewrite ^/tips/252.html$ /forums/astucesdivers/posts/terminal-compilation-java-%C3%A0-la-vol%C3%A9e permanent;
      rewrite ^/tips/269.html$ /forums/astucesdivers/posts/terminal-faire-du-grep-plus-rapidement permanent;
      rewrite ^/tips/273.html$ /forums/astucesdivers/posts/debian-shutdown-en-user permanent;
      rewrite ^/tips/255.html$ /forums/astucesdivers/posts/terminal-rajouter-le-support-du-scrollbar-%C3%A0-gnuscreen permanent;
      rewrite ^/tips/274.html$ /forums/astucesdivers/posts/terminal-qui-charge-autant-ma-machine permanent;
      rewrite ^/tips/257.html$ /forums/astucesdivers/posts/terminal-utiliser-emacs-dans-un-script permanent;
      rewrite ^/tips/258.html$ /forums/astucesdivers/posts/xkde-la-pipette-de-kde permanent;
      rewrite ^/tips/259.html$ /forums/astucesdivers/posts/debian-connection-wanadoo-avec-pack-wifi-inventel-dw-b200 permanent;
      rewrite ^/tips/260.html$ /forums/astucesdivers/posts/terminal-afficher-les-r%C3%A9pertoires-et-sous-r%C3%A9pertoires-les-plus permanent;
      rewrite ^/tips/261.html$ /forums/astucesdivers/posts/terminal-mc-et-ssh permanent;
      rewrite ^/tips/262.html$ /forums/astucesdivers/posts/debian-plusieurs-sons-en-m%C3%AAme-temps-avec-alsa permanent;
      rewrite ^/tips/263.html$ /forums/astucesdivers/posts/terminal-acpi-modifier-la-table-dsdt permanent;
      rewrite ^/tips/264.html$ /forums/astucesdivers/posts/x-window-logs-sur-le-bureau permanent;
      rewrite ^/tips/265.html$ /forums/astucesdivers/posts/ximages-modifier-tout-un-dossier-dimages-en-m%C3%AAme-temps permanent;
      rewrite ^/tips/266.html$ /forums/astucesdivers/posts/terminal-convertion-de-wma-en-wav permanent;
      rewrite ^/tips/267.html$ /forums/astucesdivers/posts/terminal-supprimer-les-mails-en-attente-dans-postfix permanent;
      rewrite ^/tips/268.html$ /forums/astucesdivers/posts/debian-supprimer-des-paquets-inutiles permanent;
      rewrite ^/tips/275.html$ /forums/astucesdivers/posts/terminal-tar-et-les-archives-multivolumes permanent;
      rewrite ^/tips/276.html$ /forums/astucesdivers/posts/webmozilla-les-news-en-un-clin-doeil permanent;
      rewrite ^/tips/289.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-xul-mode-pour-emacs permanent;
      rewrite ^/tips/290.html$ /forums/astucesdivers/posts/terminal-first-in-first-out permanent;
      rewrite ^/tips/284.html$ /forums/astucesdivers/posts/webmozilla-caract%C3%A8res-non-ascii-dans-les-url permanent;
      rewrite ^/tips/279.html$ /forums/astucesdivers/posts/web-bloquer-les-pages-de-pub permanent;
      rewrite ^/tips/280.html$ /forums/astucesdivers/posts/terminal-contr%C3%B4ler-la-taille-critique-des-r%C3%A9pertoires permanent;
      rewrite ^/tips/281.html$ /forums/astucesdivers/posts/terminal-escreen permanent;
      rewrite ^/tips/282.html$ /forums/astucesdivers/posts/x-window-d%C3%A9sactiver-le-biiiip-de-x-window permanent;
      rewrite ^/tips/283.html$ /forums/astucesdivers/posts/mail-les-news-de-linuxfrorg-sous-evolution permanent;
      rewrite ^/tips/285.html$ /forums/astucesdivers/posts/debian-verrouillage-num%C3%A9rique-presque-partout permanent;
      rewrite ^/tips/286.html$ /forums/astucesdivers/posts/debian-vous-en-avez-marre-de-voir-vos-fichiers-maison-remplac%C3%A9 permanent;
      rewrite ^/tips/291.html$ /forums/astucesdivers/posts/x-window-twinview-sdl-et-plein-%C3%A9cran permanent;
      rewrite ^/tips/292.html$ /forums/astucesdivers/posts/terminal-mutt-convivial permanent;
      rewrite ^/tips/293.html$ /forums/astucesdivers/posts/web-routeur-adsl-et-port-closed permanent;
      rewrite ^/tips/306.html$ /forums/astucesdivers/posts/perl-aller-plus-loin-avec-netserver permanent;
      rewrite ^/tips/295.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-r%C3%A9ouvrir-un-fichier-l%C3%A0-o%C3%B9-on-la-quitt%C3%A9 permanent;
      rewrite ^/tips/296.html$ /forums/astucesdivers/posts/webr%C3%A9seau-transfert-de-fichiers-le-ftp-du-geek permanent;
      rewrite ^/tips/311.html$ /forums/astucesdivers/posts/terminal-revenir-%C3%A0-son-point-de-d%C3%A9part-%C3%A0-peu-de-frais permanent;
      rewrite ^/tips/297.html$ /forums/astucesdivers/posts/web-mailto-et-spam permanent;
      rewrite ^/tips/298.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-les-raccourcis-emacs-avec-les-applications-gtk permanent;
      rewrite ^/tips/314.html$ /forums/astucesdivers/posts/webmozilla-activer-le-coller-avec-le-bouton-du-milieu permanent;
      rewrite ^/tips/307.html$ /forums/astucesdivers/posts/terminal-pages-man-dans-netscape permanent;
      rewrite ^/tips/305.html$ /forums/astucesdivers/posts/debian-personnaliser-le-menu-de-xfce4 permanent;
      rewrite ^/tips/303.html$ /forums/astucesdivers/posts/ximages-cr%C3%A9er-une-vid%C3%A9o-%C3%A0-partir-dune-s%C3%A9rie-de-photos-ou-de permanent;
      rewrite ^/tips/304.html$ /forums/astucesdivers/posts/debian-debian-tester-un-paquet-puis-le-d%C3%A9sinstaller-avec-les permanent;
      rewrite ^/tips/308.html$ /forums/astucesdivers/posts/perl-petit-script-pour-surveiller-votre-temp%C3%A9rature-de-process permanent;
      rewrite ^/tips/309.html$ /forums/astucesdivers/posts/terminal-clavier-azerty-pour-le-noyau-linux permanent;
      rewrite ^/tips/310.html$ /forums/astucesdivers/posts/terminal-restaurer-des-fichiers-supprim%C3%A9s-en-reiserfs permanent;
      rewrite ^/tips/312.html$ /forums/astucesdivers/posts/webmozilla-r%C3%A9duire-le-poids-de-firefox permanent;
      rewrite ^/tips/315.html$ /forums/astucesdivers/posts/webmozilla-gestion-facile-des-signets-avec-firefox permanent;
      rewrite ^/tips/317.html$ /forums/astucesdivers/posts/x-window-que-faire-si-l%C3%A9cran-du-portable-ne-se-r%C3%A9active-pas permanent;
      rewrite ^/tips/318.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-passer-rapidement-en-mode-commande permanent;
      rewrite ^/tips/322.html$ /forums/astucesdivers/posts/xkde-monter-des-images-iso-ou-autres-via-kde permanent;
      rewrite ^/tips/321.html$ /forums/astucesdivers/posts/debian-installer-fedora-%C3%A0-partir-des-iso-sans-les-graver permanent;
      rewrite ^/tips/323.html$ /forums/astucesdivers/posts/mail-marquer-un-mail-comme-lu-dans-un-maildir-gr%C3%A2ce-a-procmail permanent;
      rewrite ^/tips/324.html$ /forums/astucesdivers/posts/webr%C3%A9seau-tester-%C3%A0-la-main-une-connexion-internet-derri%C3%A8re-un permanent;
      rewrite ^/tips/341.html$ /forums/astucesdivers/posts/x-window-nvidia-tv-out-mplayer-vsync permanent;
      rewrite ^/tips/340.html$ /forums/astucesdivers/posts/debian-debian-pas-de-rclocal permanent;
      rewrite ^/tips/327.html$ /forums/astucesdivers/posts/web-cr%C3%A9er-un-serveur-web-une-page-sans-serveur-web permanent;
      rewrite ^/tips/328.html$ /forums/astucesdivers/posts/terminal-less-permet-de-lister-le-contenu-dune-archive permanent;
      rewrite ^/tips/329.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-table-ascii permanent;
      rewrite ^/tips/334.html$ /forums/astucesdivers/posts/perl-expressions-rationnelles-sous-adblock-extension-anti-pub permanent;
      rewrite ^/tips/331.html$ /forums/astucesdivers/posts/webr%C3%A9seau-bloquer-les-ping-sur-ipcop permanent;
      rewrite ^/tips/332.html$ /forums/astucesdivers/posts/debian-webcam-philips-toucam-2-sous-linux-24x-ou-22x-pcvc permanent;
      rewrite ^/tips/342.html$ /forums/astucesdivers/posts/web-apache-et-les-css permanent;
      rewrite ^/tips/343.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-emacs-et-les-sockets-unix permanent;
      rewrite ^/tips/348.html$ /forums/astucesdivers/posts/xkde-access-keys-sous-konqueror permanent;
      rewrite ^/tips/349.html$ /forums/astucesdivers/posts/x-window-changer-de-r%C3%A9solution-sans-red%C3%A9marrer-x permanent;
      rewrite ^/tips/350.html$ /forums/astucesdivers/posts/terminal-en-shell permanent;
      rewrite ^/tips/351.html$ /forums/astucesdivers/posts/xkde-ins%C3%A9rer-des-tabulations-dans-un-champ-texte-dune-page-w permanent;
      rewrite ^/tips/352.html$ /forums/astucesdivers/posts/terminal-substitution-multi-ligne-en-sed permanent;
      rewrite ^/tips/354.html$ /forums/astucesdivers/posts/debian-xorg-68-sur-debian permanent;
      rewrite ^/tips/355.html$ /forums/astucesdivers/posts/ximages-r%C3%A9cup%C3%A9rer-un-clip-art-au-format-wmf-windows-meta-fil permanent;
      rewrite ^/tips/356.html$ /forums/astucesdivers/posts/editeur-openoffice-et-les-bases-de-donn%C3%A9es permanent;
      rewrite ^/tips/357.html$ /forums/astucesdivers/posts/admin-capturer-une-radio-internet permanent;
      rewrite ^/tips/358.html$ /forums/astucesdivers/posts/admin-monter-un-cd-dinstallation-solaris-en-loopback-sous-lin permanent;
      rewrite ^/tips/359.html$ /forums/astucesdivers/posts/x-window-polices-%C3%A9cras%C3%A9es-sous-mozilla permanent;
      rewrite ^/tips/371.html$ /forums/astucesdivers/posts/debian-nettoyage-de-la-distribution-debian permanent;
      rewrite ^/tips/361.html$ /forums/astucesdivers/posts/terminal-prot%C3%A9ger-le-contenu-dun-r%C3%A9pertoire-contre-les-fausse permanent;
      rewrite ^/tips/362.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-abr%C3%A9viations-et-acronymes-en-xhtml permanent;
      rewrite ^/tips/391.html$ /forums/astucesdivers/posts/admin-liste-des-packages-gentoo permanent;
      rewrite ^/tips/364.html$ /forums/astucesdivers/posts/debian-probl%C3%A8mes-de-connection-r%C3%A9seau-avec-les-noyaux-268x permanent;
      rewrite ^/tips/372.html$ /forums/astucesdivers/posts/mail-liens-html-dans-thunderbird-et-courriel-dans-firefox permanent;
      rewrite ^/tips/365.html$ /forums/astucesdivers/posts/terminal-mettre-le-premier-caract%C3%A8re-dun-mot-en-majuscule-et permanent;
      rewrite ^/tips/366.html$ /forums/astucesdivers/posts/webmozilla-taille-des-polices-avec-firefox permanent;
      rewrite ^/tips/367.html$ /forums/astucesdivers/posts/x-window-modifier-les-raccourcis-clavier-de-mozilla-comme-dan permanent;
      rewrite ^/tips/368.html$ /forums/astucesdivers/posts/terminal-monter-un-fichier-nrg-comme-un-fichier-iso permanent;
      rewrite ^/tips/374.html$ /forums/astucesdivers/posts/x-window-changer-de-clavier-sans-sortir-de-x permanent;
      rewrite ^/tips/375.html$ /forums/astucesdivers/posts/x-window-molette-logitech-sous-mandrake permanent;
      rewrite ^/tips/376.html$ /forums/astucesdivers/posts/debian-marre-de-perdre-vos-fichiers-temporaires-%C3%A0-chaque-reboo permanent;
      rewrite ^/tips/377.html$ /forums/astucesdivers/posts/terminal-utiliser-chattr-avec-reiserfs permanent;
      rewrite ^/tips/378.html$ /forums/astucesdivers/posts/webmozilla-probl%C3%A8mes-de-profil-avec-firefox-thunderbird permanent;
      rewrite ^/tips/379.html$ /forums/astucesdivers/posts/debian-xorg-sous-debian-grace-%C3%A0-ubuntu permanent;
      rewrite ^/tips/380.html$ /forums/astucesdivers/posts/debian-bootsplash-sous-debian permanent;
      rewrite ^/tips/381.html$ /forums/astucesdivers/posts/debian-du-bon-ordre-dans-les-partitions permanent;
      rewrite ^/tips/404.html$ /forums/astucesdivers/posts/terminal-script-pour-t%C3%A9l%C3%A9charger-un-fichier-par-ftp permanent;
      rewrite ^/tips/405.html$ /forums/astucesdivers/posts/admin-stunnel permanent;
      rewrite ^/tips/406.html$ /forums/astucesdivers/posts/admin-nettoyer-une-mandrake-ou-une-rhfedoraetc permanent;
      rewrite ^/tips/383.html$ /forums/astucesdivers/posts/webmozilla-ouvrir-une-fen%C3%AAtre-de-composiion-mail-depuis-firef permanent;
      rewrite ^/tips/409.html$ /forums/astucesdivers/posts/terminal-sendormir-en-musique permanent;
      rewrite ^/tips/410.html$ /forums/astucesdivers/posts/webmozilla-importer-son-compte-mozilla-mail-sous-thunderbird permanent;
      rewrite ^/tips/411.html$ /forums/astucesdivers/posts/debian-tuer-x-lorsque-le-clavier-ne-r%C3%A9pond-plus permanent;
      rewrite ^/tips/412.html$ /forums/astucesdivers/posts/xkde-konqueror-ouvrir-un-nouvel-onglet-depuis-une-console permanent;
      rewrite ^/tips/413.html$ /forums/astucesdivers/posts/terminal-%C3%A9teindre-au-d%C3%A9marrage permanent;
      rewrite ^/tips/415.html$ /forums/astucesdivers/posts/webr%C3%A9seau-connecter-2-pc-en-r%C3%A9seau-firewire permanent;
      rewrite ^/tips/416.html$ /forums/astucesdivers/posts/terminal-manipulation-des-noms-de-fichiers-comportant-des-espa permanent;
      rewrite ^/tips/385.html$ /forums/astucesdivers/posts/admin-transf%C3%A9rer-son-syst%C3%A8me-dune-machine-%C3%A0-une-autre permanent;
      rewrite ^/tips/386.html$ /forums/astucesdivers/posts/admin-partager-instantan%C3%A9ment-un-screenshot permanent;
      rewrite ^/tips/387.html$ /forums/astucesdivers/posts/admin-fiabilit%C3%A9-des-%C3%A9critures-disque permanent;
      rewrite ^/tips/388.html$ /forums/astucesdivers/posts/terminal-sed-et-les-modifications-de-chemin permanent;
      rewrite ^/tips/389.html$ /forums/astucesdivers/posts/xkde-utiliser-kate-et-sa-console permanent;
      rewrite ^/tips/390.html$ /forums/astucesdivers/posts/admin-surveillance-des-varlog-sous-konsole permanent;
      rewrite ^/tips/394.html$ /forums/astucesdivers/posts/webmozilla-boost-de-firefox permanent;
      rewrite ^/tips/393.html$ /forums/astucesdivers/posts/terminal-enregistrer-un-flux-real-media permanent;
      rewrite ^/tips/395.html$ /forums/astucesdivers/posts/xkde-d%C3%A9filer-dans-tous-les-sens-avec-ou-sans-molette permanent;
      rewrite ^/tips/396.html$ /forums/astucesdivers/posts/admin-rotation-de-log-plus-claire-directement-avec-syslog-ng permanent;
      rewrite ^/tips/397.html$ /forums/astucesdivers/posts/admin-darcs-et-shfs permanent;
      rewrite ^/tips/398.html$ /forums/astucesdivers/posts/terminal-conversion-dimage-a-la-vol%C3%A9e permanent;
      rewrite ^/tips/399.html$ /forums/astucesdivers/posts/webmozilla-jai-de-la-chance permanent;
      rewrite ^/tips/400.html$ /forums/astucesdivers/posts/admin-installation-dune-distribution-fedora-via-r%C3%A9seau-pxe permanent;
      rewrite ^/tips/401.html$ /forums/astucesdivers/posts/xkde-capture-d%C3%A9cran-sous-kde permanent;
      rewrite ^/tips/407.html$ /forums/astucesdivers/posts/webmozilla-faire-en-sorte-que-firefox-utilise-kmail-pour-les permanent;
      rewrite ^/tips/408.html$ /forums/astucesdivers/posts/debian-pour-les-accros-du-tuning-changer-le-logo-au-boot permanent;
      rewrite ^/tips/421.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-vim-pour-dactylographier-avec-une-position-optimal permanent;
      rewrite ^/tips/432.html$ /forums/astucesdivers/posts/webmozilla-recherche-avanc%C3%A9e-sur-linuxfrorg permanent;
      rewrite ^/tips/419.html$ /forums/astucesdivers/posts/x-window-s%C3%A9lectionnercoller-universel-sous-x-historiques permanent;
      rewrite ^/tips/431.html$ /forums/astucesdivers/posts/webmozilla-firefox-et-les-recherches-perso permanent;
      rewrite ^/tips/422.html$ /forums/astucesdivers/posts/debian-xorg-kde-sous-debian-sidsarge permanent;
      rewrite ^/tips/425.html$ /forums/astucesdivers/posts/webmozilla-firefox-plusieurs-pages-au-d%C3%A9marrage permanent;
      rewrite ^/tips/430.html$ /forums/astucesdivers/posts/x-window-avoir-lheure-de-plusieurs-pays permanent;
      rewrite ^/tips/445.html$ /forums/astucesdivers/posts/webr%C3%A9seau-wifi-usb-automatis%C3%A9 permanent;
      rewrite ^/tips/446.html$ /forums/astucesdivers/posts/x-window-top-xrootconsole permanent;
      rewrite ^/tips/434.html$ /forums/astucesdivers/posts/admin-xchat-avec-plusieurs-charset permanent;
      rewrite ^/tips/435.html$ /forums/astucesdivers/posts/webmozilla-ins%C3%A9rer-des-tabulations-dans-un-champ-texte-dun-f permanent;
      rewrite ^/tips/429.html$ /forums/astucesdivers/posts/admin-firewall-iptables-minimal-mais-efficace permanent;
      rewrite ^/tips/436.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-compl%C3%A9tion-des-noms-de-fonction-dans-un-source permanent;
      rewrite ^/tips/500.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-transformer-un-buffer-avec-coloration-syntaxique permanent;
      rewrite ^/tips/438.html$ /forums/astucesdivers/posts/webmozilla-fiferox-afficher-les-t%C3%A9l%C3%A9chargements-dans-le-vole permanent;
      rewrite ^/tips/439.html$ /forums/astucesdivers/posts/terminal-compter-le-nombre-de-fichiers-par-extension-dans-un-r permanent;
      rewrite ^/tips/440.html$ /forums/astucesdivers/posts/admin-mise-%C3%A0-jour-globale-dune-slackware-avec-slackpkg permanent;
      rewrite ^/tips/441.html$ /forums/astucesdivers/posts/terminal-exclure-un-sous-dossier-dune-copie-recursive permanent;
      rewrite ^/tips/442.html$ /forums/astucesdivers/posts/terminal-exploiter-lhistorique-du-shell permanent;
      rewrite ^/tips/443.html$ /forums/astucesdivers/posts/xgnome-switcher-esd-onoff permanent;
      rewrite ^/tips/444.html$ /forums/astucesdivers/posts/xgnome-le-poste-de-travail-de-gnome permanent;
      rewrite ^/tips/447.html$ /forums/astucesdivers/posts/web-les-filtres-de-liferea permanent;
      rewrite ^/tips/450.html$ /forums/astucesdivers/posts/xgnome-placement-collant-des-fen%C3%AAtres-sous-gnome permanent;
      rewrite ^/tips/451.html$ /forums/astucesdivers/posts/webmozilla-smart-bookmark-firefox permanent;
      rewrite ^/tips/498.html$ /forums/astucesdivers/posts/admin-forcer-une-interface-r%C3%A9seau-en-100-full-duplex-sans-auto permanent;
      rewrite ^/tips/499.html$ /forums/astucesdivers/posts/perl-script-de-ping-pour-technorati-et-consort permanent;
      rewrite ^/tips/454.html$ /forums/astucesdivers/posts/xkde-de-belles-grandes-ic%C3%B4nes-dans-le-menu-de-kde permanent;
      rewrite ^/tips/460.html$ /forums/astucesdivers/posts/webmozilla-acc%C3%A9l%C3%A9rer-la-r%C3%A9solution-dns-de-firefox permanent;
      rewrite ^/tips/469.html$ /forums/astucesdivers/posts/webmozilla-clic-bouton-du-milieu-avec-firefox-pour-fermer-les permanent;
      rewrite ^/tips/464.html$ /forums/astucesdivers/posts/terminal-chargement-en-cha%C3%AEne-des-modules-kernel permanent;
      rewrite ^/tips/467.html$ /forums/astucesdivers/posts/web-firefox-clic-du-milieu-g%C3%A9n%C3%A9ralis%C3%A9 permanent;
      rewrite ^/tips/466.html$ /forums/astucesdivers/posts/x-window-la-souris-pour-les-gauchers permanent;
      rewrite ^/tips/468.html$ /forums/astucesdivers/posts/web-firefox-gestion-des-bookmarks-dans-un-onglet permanent;
      rewrite ^/tips/470.html$ /forums/astucesdivers/posts/admin-changer-al%C3%A9atoirement-de-cl%C3%A9-wep-au-d%C3%A9marrage permanent;
      rewrite ^/tips/471.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-choisir-un-encodage-par-projets permanent;
      rewrite ^/tips/472.html$ /forums/astucesdivers/posts/terminal-bookmarker-des-r%C3%A9pertoires-avec-cdargs permanent;
      rewrite ^/tips/476.html$ /forums/astucesdivers/posts/admin-comparer-deux-r%C3%A9pertoires permanent;
      rewrite ^/tips/477.html$ /forums/astucesdivers/posts/editeur-saisie-unicode-dans-scribus permanent;
      rewrite ^/tips/478.html$ /forums/astucesdivers/posts/ximages-conversion-svg-ps-avec-pseudo-transparence permanent;
      rewrite ^/tips/479.html$ /forums/astucesdivers/posts/x-window-gdm-et-haltreboot-sans-gnome permanent;
      rewrite ^/tips/496.html$ /forums/astucesdivers/posts/debian-mise-%C3%A0-jour-sioux-s%C3%A9lective permanent;
      rewrite ^/tips/483.html$ /forums/astucesdivers/posts/debian-connaissez-vous-modules-assistant permanent;
      rewrite ^/tips/484.html$ /forums/astucesdivers/posts/x-window-comment-enlever-asus-acpi-error-reading-lcd-statu permanent;
      rewrite ^/tips/497.html$ /forums/astucesdivers/posts/webr%C3%A9seau-bypasser-tr%C3%A9s-simplement-un-proxy permanent;
      rewrite ^/tips/488.html$ /forums/astucesdivers/posts/xgnome-esd-et-le-son-en-r%C3%A9seau permanent;
      rewrite ^/tips/489.html$ /forums/astucesdivers/posts/d%C3%A9veloppement-perdu-dans-les-drapeaux-doptimisation-de-gcc permanent;
      rewrite ^/tips/490.html$ /forums/astucesdivers/posts/admin-backups-mouvants-utilisez-rsync permanent;
      rewrite ^/tips/491.html$ /forums/astucesdivers/posts/admin-recherche-dinformations-dans-le-noyau permanent;
      rewrite ^/tips/494.html$ /forums/astucesdivers/posts/xkde-konsole-nommage-contextuel-intelligent-des-onglets permanent;
      rewrite ^/tips/501.html$ /forums/astucesdivers/posts/terminal-pourquoi-xterm-a-des-couleurs-dans-les-man permanent;
      rewrite ^/tips/502.html$ /forums/astucesdivers/posts/webr%C3%A9seau-probl%C3%A8me-dhorloge-avec-proftpd permanent;
      rewrite ^/tips/503.html$ /forums/astucesdivers/posts/admin-faire-le-m%C3%A9nage-dans-les-dossiers permanent;
      rewrite ^/tips/504.html$ /forums/astucesdivers/posts/admin-traiter-des-fichiers-mdb-access permanent;
      rewrite ^/tips/505.html$ /forums/astucesdivers/posts/perl-modifier-un-pdf-avec-perl permanent;
      rewrite ^/tips/507.html$ /forums/astucesdivers/posts/x-window-quand-vous-appuyez-sur-vous-avez permanent;
      rewrite ^/tips/508.html$ /forums/astucesdivers/posts/web-passer-tout-un-site-dun-encodage-%C3%A0-un-autre permanent;
      rewrite ^/tips/514.html$ /forums/astucesdivers/posts/debian-purger-sa-debian-reprendre-le-contr%C3%B4le permanent;
      rewrite ^/tips/515.html$ /forums/astucesdivers/posts/admin-convertir-son-fs-linux-ext2ext3-iso-8859-15-au-format-u permanent;
      rewrite ^/tips/516.html$ /forums/astucesdivers/posts/editeur-formulaire-pdf permanent;
      rewrite ^/tips/517.html$ /forums/astucesdivers/posts/webmozilla-firefox-15-d%C3%A9sactiv%C3%A9-les-miniatures-dimage-en permanent;
      rewrite ^/tips/518.html$ /forums/astucesdivers/posts/xkde-retrouver-les-onglets-ouverts-apr%C3%A8s-un-crash-de-konquero permanent;
      rewrite ^/tips/519.html$ /forums/astucesdivers/posts/admin-compl%C3%A9tion-avec-ksh permanent;
      rewrite ^/tips/520.html$ /forums/astucesdivers/posts/xgnome-utiliser-le-dictionnaire-de-gnome-en-fran%C3%A7ais permanent;
      rewrite ^/tips/522.html$ /forums/astucesdivers/posts/%C3%A9diteuremacs-voir-ses-modifs-sous-emacs-depuis-louverture-du permanent;
      rewrite ^/tips/523.html$ /forums/astucesdivers/posts/terminal-rediffuser-un-terminal-en-direct permanent;
      rewrite ^/tips/524.html$ /forums/astucesdivers/posts/webmozilla-thunderbird-classer-ses-courriels-par-jour permanent;
      rewrite ^/tips/525.html$ /forums/astucesdivers/posts/debianadmin-auto-apt-pour-resoudre-les-dependances permanent;
      rewrite ^/tips/530.html$ /forums/astucesdivers/posts/terminal-fusionner-les-lignes-dun-texte permanent;
      rewrite ^/tips/528.html$ /forums/astucesdivers/posts/xkde-bouton-fermer-longlet-dans-konqueror permanent;
      rewrite ^/tips/529.html$ /forums/astucesdivers/posts/terminal-un-undelete-basique permanent;
      rewrite ^/tips/531.html$ /forums/astucesdivers/posts/editeur-blue-fish permanent;
      rewrite ^/tips/532.html$ /forums/astucesdivers/posts/admin-autofs-et-sshfs-fuse permanent;
      rewrite ^/tips/534.html$ /forums/astucesdivers/posts/d%C3%A9veloppement-supprimer-les-dossiers-vides-g%C3%A9n%C3%A9r%C3%A9s-par-doxygen permanent;
      rewrite ^/tips/535.html$ /forums/astucesdivers/posts/terminal-rlwrap permanent;
      rewrite ^/tips/536.html$ /forums/astucesdivers/posts/webmozilla-firefox-s%C3%A9lection-de-cellules-dun-tableau permanent;
      rewrite ^/tips/537.html$ /forums/astucesdivers/posts/admin-traquer-les-fichiers-gourmands-en-espace-disque permanent;
      rewrite ^/tips/538.html$ /forums/astucesdivers/posts/debian-scanbuttond permanent;
      rewrite ^/tips/539.html$ /forums/astucesdivers/posts/webmozilla-d%C3%A9sactiver-la-restauration-de-session-sous-bon-ech permanent;
      rewrite ^/tips/540.html$ /forums/astucesdivers/posts/xkde-personnaliser-larr%C3%AAt-de-kde permanent;
      rewrite ^/tips/541.html$ /forums/astucesdivers/posts/d%C3%A9veloppement-choisir-o%C3%B9-et-sous-quel-nom-sont-cr%C3%A9%C3%A9s-les-cored permanent;
      rewrite ^/tips/542.html$ /forums/astucesdivers/posts/admin-lancer-une-applis-root-sous-x permanent;
      rewrite ^/tips/543.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-les-buffeurs-ca-change-la-vie permanent;
      rewrite ^/tips/584.html$ /forums/astucesdivers/posts/admin-ajouter-une-clef-ssh-en-une-ligne permanent;
      rewrite ^/tips/585.html$ /forums/astucesdivers/posts/admin-completion-pour-connexion-ssh-tcsh permanent;
      rewrite ^/tips/545.html$ /forums/astucesdivers/posts/webr%C3%A9seau-utiliser-un-dns-public permanent;
      rewrite ^/tips/546.html$ /forums/astucesdivers/posts/webr%C3%A9seau-amule-daemon-de-mani%C3%A8re-intelligente permanent;
      rewrite ^/tips/548.html$ /forums/astucesdivers/posts/xkde-changer-le-titre-dun-onglet-konsole-lors-dune-connexio permanent;
      rewrite ^/tips/549.html$ /forums/astucesdivers/posts/webmozilla-firefox-20-backspace-remonte-la-page-au-lieu-de permanent;
      rewrite ^/tips/550.html$ /forums/astucesdivers/posts/xkde-fermer-les-onglets-avec-le-bouton-du-milieu-sous-konquer permanent;
      rewrite ^/tips/554.html$ /forums/astucesdivers/posts/xgnome-wine-association-des-fichiers permanent;
      rewrite ^/tips/556.html$ /forums/astucesdivers/posts/xkde-ajout-de-raccourci-dans-lapplet-menu-du-syst%C3%A8me permanent;
      rewrite ^/tips/557.html$ /forums/astucesdivers/posts/x-window-des-astuces-pour-rox-filer permanent;
      rewrite ^/tips/558.html$ /forums/astucesdivers/posts/admin-enregistrer-la-sortie-audio-dans-un-fichier permanent;
      rewrite ^/tips/573.html$ /forums/astucesdivers/posts/web-wget-et-cookie-dlfreefr permanent;
      rewrite ^/tips/574.html$ /forums/astucesdivers/posts/ximages-pdftosvg permanent;
      rewrite ^/tips/575.html$ /forums/astucesdivers/posts/xkde-une-page-de-d%C3%A9marrage-personnalis%C3%A9e-pour-chaque-profil-d permanent;
      rewrite ^/tips/560.html$ /forums/astucesdivers/posts/webr%C3%A9seau-proxy-ssh permanent;
      rewrite ^/tips/561.html$ /forums/astucesdivers/posts/mail-mutt-et-messages-sign%C3%A9sencrypt%C3%A9s-pgp-non-mime permanent;
      rewrite ^/tips/582.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-utiliser-les-splits permanent;
      rewrite ^/tips/583.html$ /forums/astucesdivers/posts/debian-flash-plugin-pour-debian-etch permanent;
      rewrite ^/tips/563.html$ /forums/astucesdivers/posts/d%C3%A9veloppement-pseudo-polymorphisme-en-c permanent;
      rewrite ^/tips/564.html$ /forums/astucesdivers/posts/terminal-impression-directe-sans-installation-via-ftp permanent;
      rewrite ^/tips/566.html$ /forums/astucesdivers/posts/webr%C3%A9seau-utiliser-un-deuxi%C3%A8me-serveur-pour-des-adresses-ip-s permanent;
      rewrite ^/tips/567.html$ /forums/astucesdivers/posts/admin-monter-la-partition-dune-image-disque-en-loopback permanent;
      rewrite ^/tips/568.html$ /forums/astucesdivers/posts/d%C3%A9veloppement-gdb-et-le-mode-visuel-cach%C3%A9 permanent;
      rewrite ^/tips/570.html$ /forums/astucesdivers/posts/admin-serveur-samba-qui-utilise-le-fichier permanent;
      rewrite ^/tips/572.html$ /forums/astucesdivers/posts/obsol%C3%A8te-poster-du-code-dans-les-commentaires-astuces-etc-de-linuxfr permanent;
      rewrite ^/tips/576.html$ /forums/astucesdivers/posts/debian-faire-un-packet-pour-un-logiciel-compil%C3%A9-%C3%A0-la-main permanent;
      rewrite ^/tips/577.html$ /forums/astucesdivers/posts/admin-construire-des-mots-de-passe-forts-mais-facilement-recon permanent;
      rewrite ^/tips/578.html$ /forums/astucesdivers/posts/webr%C3%A9seau-socat permanent;
      rewrite ^/tips/579.html$ /forums/astucesdivers/posts/terminal-mon-environnement-shell permanent;
      rewrite ^/tips/580.html$ /forums/astucesdivers/posts/%C3%A9diteurvim-correction-orthographique-avec-vim permanent;
      rewrite ^/tips/581.html$ /forums/astucesdivers/posts/webr%C3%A9seau-connection-ssh-simplifi%C3%A9e-%C3%A0-travers-un-tunnel permanent;
      rewrite ^/tips/587.html$ /forums/astucesdivers/posts/admin-utiliser-bind9-pour-eviter-les-problemes-de-dns permanent;
      rewrite ^/tips/589.html$ /forums/astucesdivers/posts/xkde-flash-player-90115-et-konqueror permanent;
      rewrite ^/tips/588.html$ /forums/astucesdivers/posts/terminal-limiter-la-vitesse-dun-lecteur-de-cddvd permanent;
      rewrite ^/tips/590.html$ /forums/astucesdivers/posts/terminal-extraire-le-son-dune-vid%C3%A9o permanent;
    }
}

# No-TLS
server {
    server_name <%= fqdn %>;
    listen 80 default_server;
    rewrite ^/(.*) https://<%= fqdn %>/$1 permanent;
}

# No-www
server {
    server_name www.<%= fqdn %>;
    listen 80;
    listen 443;
    ssl_certificate ssl.crt/<%= fqdn %>.crt;
    ssl_certificate_key ssl.key/<%= fqdn %>.key;
    rewrite ^/(.*) $scheme://<%= fqdn %>/$1 permanent;
}
