#! /bin/sh
### BEGIN INIT INFO
# Provides:          board
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the board daemon
### END INIT INFO
#
# Install with: insserv board

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
CONTAINER=prod
HOME=/data/$CONTAINER/$USER
BDIR=$HOME/board
PIDFILE=$BDIR/board.pid
DAEMON=board-linuxfr
ARGS="-d -v -S $BDIR/board.sock -l $BDIR/board.log -P $PIDFILE"

as_user() {
  if [ "xroot" != "x`whoami`" ]
  then
    bash -c "$2"
  else
    su - -c "$2" $1
  fi
}

case "$1" in
  start)
    echo "Starting board for user '$USER'"
    as_user $USER "source ~/ruby-env; cd $BDIR; $DAEMON $ARGS"
    echo "."
    ;;

  stop)
    echo "Stopping board for user '$USER'"
    kill -QUIT `cat $PIDFILE`
    echo "."
    ;;

  restart)
    echo "Restarting board for user '$USER'"
    kill -QUIT `cat $PIDFILE`
    sleep 2
    rm -f $PIDFILE
    as_user $USER "source ~/ruby-env; cd $BDIR; $DAEMON $ARGS"
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/board {start|stop|restart}"
    exit 1
esac
