#! /bin/sh
### BEGIN INIT INFO
# Provides:          board
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the board daemon
### END INIT INFO
#
# Install with: update-rc.d board defaults 99

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
HOME=/var/www/$USER

case "$1" in
  start)
    echo "Starting board for user '$USER'"
    su -l -c "source ~/ruby-env; cd $HOME/board; ruby -Ilib ./bin/board.rb" $USER
    echo "."
    ;;

  stop)
    echo "Stopping board for user '$USER'"
    kill -QUIT `cat $HOME/board/board.pid`
    echo "."
    ;;

  restart)
    echo "Restarting board for user '$USER'"
    kill -QUIT `cat $HOME/board/board.pid`
    sleep 1
    su -l -c "source ~/ruby-env; cd $HOME/board; ruby -Ilib ./bin/board.rb" $USER
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/board {start|stop|restart}"
    exit 1
esac

exit 0
