#! /bin/sh
### BEGIN INIT INFO
# Provides:          img
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the img daemon
### END INIT INFO
#
# Install with: update-rc.d img defaults 99

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
CONTAINER=prod
HOME=/data/$CONTAINER/$USER
LOG=/data/$CONTAINER/logs/img/img.log
NAME=img-LinuxFr.org
DAEMON=$HOME/go/bin/$NAME
DAEMON_OPTS="-l $LOG -d $HOME/img"
PIDFILE=/var/run/$NAME.pid

case "$1" in
  start)
    echo "Starting $NAME"
	start-stop-daemon --start --background --make-pidfile --quiet \
		--pidfile $PIDFILE --chuid $USER:$USER \
		--exec $DAEMON -- $DAEMON_OPTS || true
    echo "."
    ;;

  stop)
    echo "Stopping $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE || true
    echo "."
    ;;

  restart)
    echo "Restarting $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE || true
    sleep 2
	start-stop-daemon --start --background --make-pidfile --quiet \
		--pidfile $PIDFILE --chuid $USER:$USER \
		--exec $DAEMON -- $DAEMON_OPTS || true
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/img {start|stop|restart}"
    exit 1
esac

exit 0
