#! /bin/sh
### BEGIN INIT INFO
# Provides:          img
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the img daemon
### END INIT INFO
#
# Install with: update-rc.d img defaults 99

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
CONTAINER=prod
RAILS_ENV=production
HOME=/data/$CONTAINER/$USER
NAME=img-LinuxFr.org
DAEMON=$HOME/go/bin/$NAME
SECRET=$(awk '/images/ {print $2}' $HOME/$RAILS_ENV/shared/config/secret.yml)
DAEMON_OPTS="-s $SECRET -d $HOME/img"
PIDFILE=/var/run/$NAME.pid

case "$1" in
  start)
    echo "Starting $NAME"
	start-stop-daemon --start --background --make-pidfile --quiet \
		--pidfile $PIDFILE --chuid $USER:$USER \
		--exec $DAEMON -- $DAEMON_OPTS || true
    echo "."
    ;;

  stop)
    echo "Stopping $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
    echo "."
    ;;

  restart)
    echo "Restarting $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--exec $DAEMON -- $DAEMON_OPTS || true
    sleep 2
	start-stop-daemon --start --background --make-pidfile --quiet \
		--pidfile $PIDFILE --chuid $USER:$USER \
		--exec $DAEMON -- $DAEMON_OPTS || true
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/img {start|stop|restart}"
    exit 1
esac

exit 0
