#! /bin/sh
### BEGIN INIT INFO
# Provides:          svgtex
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the svgtex daemon
### END INIT INFO
#
# Install with: insserv svgtex

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
CONTAINER=prod
HOME=/data/$CONTAINER/$USER
LOG=/data/$CONTAINER/logs/svgtex/svtex.log
NAME=svgtex
DAEMON=phantomjs
DAEMON_OPTS="main.js"
PIDFILE=/var/run/$NAME.pid

set -e

case "$1" in
  start)
    echo "Starting $NAME"
	start-stop-daemon --start --background --make-pidfile --quiet \
		--no-close --pidfile $PIDFILE --chuid $USER:$USER \
		--exec $DAEMON -- $DAEMON_OPTS > $LOG 2>&1
    echo "."
    ;;

  stop)
    echo "Stopping $NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;

  restart)
    echo "Restarting $NAME"
	start-stop-daemon --stop --retry 10 --quiet --pidfile $PIDFILE
	start-stop-daemon --start --background --make-pidfile --quiet \
		--no-close --pidfile $PIDFILE --chuid $USER:$USER \
		--exec $DAEMON -- $DAEMON_OPTS > $LOG 2>&1
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/epub {start|stop|restart}"
    exit 1
esac
