#!/bin/sh
### BEGIN INIT INFO
# Provides:          thin
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop thin instances
### END INIT INFO
#
# Install with: update-rc.d thin defaults 99

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
HOME=/var/www/$USER
DAEMON=$HOME/gem/bin/thin
DAEMON_ARGS="-C $HOME/admin/conf/thin/rails.yml"

case "$1" in
  start)
    echo "Starting Thin instances for user '$USER'"
    su -l -c "source ~/ruby-env; $DAEMON $DAEMON_ARGS start" $USER
    echo "."
    ;;
  stop)
    echo "Stopping Thin instances for user '$USER'"
    su -l -c "source ~/ruby-env; $DAEMON $DAEMON_ARGS stop" $USER
    echo "."
    ;;
  restart)
    echo "Restarting Thin instances for user '$USER'"
    su -l -c "source ~/ruby-env; $DAEMON $DAEMON_ARGS restart" $USER
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/thin {start|stop|reload|restart}"
    exit 1
esac

exit 0
