#! /bin/sh
### BEGIN INIT INFO
# Provides:          unicorn
# Required-Start:    $local_fs $remote_fs $network $nginx
# Required-Stop:     $local_fs $remote_fs $network $nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the unicorn web server
### END INIT INFO
#
# Install with: insserv unicorn

PATH=/bin:/usr/bin:/sbin:/usr/sbin
USER=linuxfr
CONTAINER=prod
HOME=/data/$CONTAINER/$USER
RAILS_ENV=production
DAEMON=unicorn
DAEMON_ARGS="-c $HOME/$RAILS_ENV/current/config/unicorn.rb -D"
PIDFILE=$HOME/$RAILS_ENV/shared/pids/unicorn.pid

as_user() {
  if [ "xroot" != "x`whoami`" ]
  then
    bash -c "$2"
  else
    su - -c "$2" $1
  fi
}

case "$1" in
  start)
    echo "Starting unicorn for user '$USER'"
    as_user $USER "source ~/ruby-env; cd $HOME/$RAILS_ENV/current; bundle exec $DAEMON $DAEMON_ARGS"
    echo "."
    ;;

  stop)
    echo "Stopping unicorn for user '$USER'"
    kill -QUIT `cat $PIDFILE`
    echo "."
    ;;

  restart)
    echo "Restarting unicorn for user '$USER'"
    PID=`cat $PIDFILE`
    kill -USR2 $PID
    sleep 1
    kill -QUIT $PID
    echo "."
    ;;

  reload)
    echo "Reloading unicorn configuration for user '$USER'"
    kill -HUP `cat $PIDFILE`
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/unicorn {start|stop|reload|restart}"
    exit 1
esac
